export const ALL_DOCUMENTS = 'ALL_DOCUMENTS'
export const MY_DOCUMENTS = 'MY_DOCUMENTS'
export const DOCUMENTS_SHARE_WITH_ME = 'DOCUMENTS_SHARE_WITH_ME'
export const CHECKED_OUT_DOCUMENTS = 'CHECKED_OUT_DOCUMENTS'
export const ARCHIVED_DOCUMENTS = 'ARCHIVED_DOCUMENTS'
export const ASCENDING = 'asc'
export const DESCENDING = 'desc'
export const ASSET_NAME = 'asset_name'
export const MODIFICATION_DATE = 'modification_date'
export const ERROR = 'Error'
export const INFO = 'Info'
export const WARNING = 'Warning'
export const FATAL = 'Fatal'
export const DEBUG = 'Debug'
export const GENERAL_FAMILY = 'General'
export const SUCCESS = 'success'
export const ACCESS_KEY = '743AA96A-0EDD-4A19-BC19-3D6778D08901'



