# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'kenesto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
     pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
     pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'
     pod 'RSKImageCropper'
     pod 'QBImagePickerController'
     pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'
     pod 'React', path: '../node_modules/react-native', subspecs: ['ART',]
     pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
     pod 'FPPicker', '~> 5.1.6'
     pod 'Firebase/Core'
     pod 'Firebase/Messaging'
  # Pods for kenesto

 # target 'kenestoTests' do
 #   inherit! :search_paths
    
    # Pods for testing
 # end

end
